/**
 * Generate the migration that back-fills the built-in legal pages
 * (/privacy-policy, /terms-of-service) for sites that already exist.
 *
 * Usage: npx tsx scripts/generate-legal-pages-migration.ts
 *
 * The widget snapshots are emitted from pageDefaults.ts rather than written by
 * hand. Migration 0072 hardcoded a copy of the footer config, the defaults
 * moved on to v3, and the two drifted — that is the bug this migration exists
 * to clean up, so the snapshot is generated instead of transcribed.
 *
 * The migration is a point-in-time back-fill. Later changes to the default
 * copy travel the normal way: bump CURRENT_BUILTIN_VERSION and let the
 * seeding service publish a new default revision.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { BUILTIN_PAGES, LEGAL_BUILTIN_PAGE_SLUGS } from '../src/lib/utils/editor/pageDefaults';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const MIGRATION_NAME = '0103_seed_builtin_legal_pages';

/**
 * Read CURRENT_BUILTIN_VERSION out of the seeding module's source.
 *
 * Importing it would drag in the whole server db layer (nanoid, the D1 types,
 * the $lib aliases) for the sake of one integer, and this script runs outside
 * the SvelteKit resolver.
 */
function currentBuiltinVersion(): number {
  const source = fs.readFileSync(
    path.join(__dirname, '..', 'src', 'lib', 'server', 'db', 'builtin-seeding.ts'),
    'utf8'
  );
  const match = source.match(/export const CURRENT_BUILTIN_VERSION = (\d+);/);
  if (!match) {
    throw new Error('Could not read CURRENT_BUILTIN_VERSION from builtin-seeding.ts');
  }
  return parseInt(match[1], 10);
}

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''");
}

function generateMigration(): string {
  const version = currentBuiltinVersion();
  const lines: string[] = [];

  lines.push(`-- Migration: ${MIGRATION_NAME}`);
  lines.push('-- Description: Create the built-in Privacy Policy and Terms of Service pages for');
  lines.push('-- every existing site, with a published revision each.');
  lines.push('--');
  lines.push('-- The default footer has linked to /privacy-policy and /terms-of-service since');
  lines.push('-- 0072, but no migration ever created them, so both 404 on every storefront');
  lines.push('-- (issue #72). 0073 updates these page ids without anything inserting them and');
  lines.push('-- has been a no-op since it landed.');
  lines.push('--');
  lines.push('-- Generated by scripts/generate-legal-pages-migration.ts from pageDefaults.ts.');
  lines.push('-- Do not edit by hand; re-run the script instead.');
  lines.push('--');
  lines.push('-- Rollback:');
  lines.push(
    "--   DELETE FROM page_revisions WHERE notes = 'Default configuration v" + version + "'"
  );
  lines.push(
    "--     AND page_id IN (SELECT id FROM pages WHERE slug IN ('/privacy-policy', '/terms-of-service'));"
  );
  lines.push(
    "--   DELETE FROM pages WHERE slug IN ('/privacy-policy', '/terms-of-service') AND is_builtin = 1;"
  );
  lines.push('');

  const definitions = BUILTIN_PAGES.filter((p) => LEGAL_BUILTIN_PAGE_SLUGS.includes(p.slug));

  for (const definition of definitions) {
    const snapshot = JSON.stringify(definition.getWidgets());
    const title = escapeSQL(definition.title);
    const slug = escapeSQL(definition.slug);

    lines.push(`-- ${definition.title} (${definition.slug})`);
    lines.push('--');
    lines.push('-- The id matches seedBuiltinPage: the bare builtin id on default-site, and');
    lines.push('-- suffixed with the site id everywhere else, because pages.id is a global key.');
    lines.push('-- Skipped for any site that already has a page on this slug, so a tenant who');
    lines.push('-- already wrote their own policy keeps it.');
    lines.push(
      'INSERT INTO pages (id, site_id, title, slug, status, is_builtin, created_at, updated_at)'
    );
    lines.push('SELECT');
    lines.push(`  CASE WHEN s.id = 'default-site' THEN '${escapeSQL(definition.id)}'`);
    lines.push(`       ELSE '${escapeSQL(definition.id)}--' || s.id END,`);
    lines.push('  s.id,');
    lines.push(`  '${title}',`);
    lines.push(`  '${slug}',`);
    lines.push("  'published',");
    lines.push('  1,');
    lines.push("  strftime('%s', 'now'),");
    lines.push("  strftime('%s', 'now')");
    lines.push('FROM sites s');
    lines.push('WHERE NOT EXISTS (');
    lines.push(`  SELECT 1 FROM pages p WHERE p.site_id = s.id AND p.slug = '${slug}'`);
    lines.push(');');
    lines.push('');

    lines.push(`-- Published revision for ${definition.title}.`);
    lines.push('-- getPublishedRevision reads page_revisions.is_published, so the page only');
    lines.push('-- renders once this row exists.');
    lines.push('INSERT INTO page_revisions (');
    lines.push('  id, page_id, revision_hash, parent_revision_id,');
    lines.push('  title, slug, status, widgets_snapshot,');
    lines.push('  created_by, created_at, is_published, notes');
    lines.push(')');
    lines.push('SELECT');
    lines.push(`  p.id || '-rev-${version}',`);
    lines.push('  p.id,');
    lines.push('  substr(lower(hex(randomblob(8))), 1, 8),');
    lines.push('  NULL,');
    lines.push(`  '${title}',`);
    lines.push(`  '${slug}',`);
    lines.push("  'published',");
    lines.push(`  '${escapeSQL(snapshot)}',`);
    lines.push("  'system',");
    lines.push("  strftime('%s', 'now'),");
    lines.push('  1,');
    lines.push(`  'Default configuration v${version}'`);
    lines.push('FROM pages p');
    lines.push(`WHERE p.slug = '${slug}'`);
    lines.push('  AND p.is_builtin = 1');
    lines.push('  AND NOT EXISTS (');
    lines.push('    SELECT 1 FROM page_revisions r WHERE r.page_id = p.id AND r.is_published = 1');
    lines.push('  );');
    lines.push('');
  }

  return lines.join('\n');
}

const migrationPath = path.join(__dirname, '..', 'migrations', `${MIGRATION_NAME}.sql`);
fs.writeFileSync(migrationPath, generateMigration());
console.log(`Migration written to: ${migrationPath}`);
console.log('\nTo apply it locally, run:');
console.log('  npm run db:migrate:local');
